# Generated by Django 4.1.1 on 2022-10-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_assets_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='ipfs_url',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
