# Generated by Django 4.1.1 on 2022-10-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_assets_ipfs_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='asset_name',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
